blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/TheWidlarzGroup/react-native-video-player/discussions
    about: Please ask and answer questions here.
  - name: TheWidlarzGroup Discord
    url: https://discord.gg/7Y6eE62hXM
    about: Feel free to join our Discord server and ask questions there.
